### ISSUE TITLE
Installer Error - file already exist, version(2.0.608.3)

### ISSUE THREAD

**Issue by Starcounter-Jack** [Polyjuice/Polyjuice#3] opened 2014-12-08 13:31 UTC
```
Error occurred during installation:

System.IO.DirectoryNotFoundException: Could not find a part of the path 
'c:\Starcounter\Personal\Personal.server.config'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Starcounter.Advanced.Configuration.ConfigurationFile.Load[T](String fileName)
   at Starcounter.InstallerEngine.CPersonalServer.Install()
   at Starcounter.InstallerEngine.InstallerMain.InstallAllComponents()
   at Starcounter.InstallerEngine.InstallerMain.StarcounterSetup(String[] args, String binariesPath, String setupConfigFile, EventHandler`1 progressCallback, EventHandler`1 messageboxCallback)

Running rollback...
```

**Comment by warpech** [comment] 2015-06-18 11:39
@miyconst could you check if this is still reproducible? I couldn't reproduce it

**Comment by miyconst** [comment] 2015-06-18 12:09
@warpech how can I check it? I don't have access to the `2.0.608.3`. Just now installed/uninstalled a couple of times different versions, no issue so far.

Also I have never met such error.

**Comment by warpech** [comment] 2015-06-18 12:25
By "still reproducible" I mean the current version (2.0.3226.3).

I am also not able to reproduce it, even when providing an unexisting path to the installer (`C:\aaa\bbb\db`, while `C:\aaa` does not exist). The installation went fine.

Closing as not reproducible anymore.

**Comment by warpech** [comment] 2015-06-18 12:29
Reopening, because I would like @andwah to check if he is able to find any suspicious code in the installer, even though for us it is not reproducible. As an essay says, ["Trust the anecdote"](http://www.codypowell.com/taods/2015/06/trust-the-anecdote.html)

@andwah please close this if you cannot find possible error in code

**Comment by andwah** [comment] 2015-06-18 15:35
I can confirm that this is still valid, i manage to force this exception.  ill take a look

**Comment by warpech** [comment] 2016-06-22 14:46
@andwah, can this issue be closed now?

**Comment by warpech** [comment] 2016-06-22 14:46
Closing as outdated. We are not using the word Polyjuice at all right now

**Comment by warpech** [comment] 2017-05-17 14:37
Closing. If this was still an issue, it would be reported in Starcounter repo.

**Closed by warpech** 2017-05-17 14:37 UTC
